version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.05"
          memory: 128M
      mode: global

